# Generated by Django 2.0.6 on 2018-06-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingdiscuss', '0002_sharingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='discuss_images/')),
            ],
        ),
        migrations.AddField(
            model_name='sharingitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='share_images/'),
        ),
    ]
